title = "clavis-cli"
description = "Lightweight, opinionated, paranoid, k8s-native secrets management"
url = "https://github.com/adrianchifor/clavis"
version = "0.1.0"
author = "Adrian Chifor"
author_email = "me@adrianchifor.com"
license = "GNU General Public License v3.0"
